[project]
name = "passtw"
version = "0.1.0"
dependencies = [
    "click",
    "cryptography",
]

[tool.setuptools]
packages = ["src"]

[tool.setuptools.package-dir]
src = "src"

[project.scripts]
passtw = "src.cli:passtw"
